# Generated by Django 4.1.6 on 2023-02-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_stu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sty_branch',
            new_name='stu_branch',
        ),
    ]
